// src/data/generatedWords.ts
//
// AUTO-GENERATED by scripts/generate-audio.mjs — do not edit by hand.
// 这里是占位文件, 第一次跑 npm run audio 之后会被真实数据覆盖。
// 字段:
//   {word, begin(ms), end(ms), charBegin, charEnd}
// 中文是字级 (word_end - word_begin = 1), 不需要音节合并。

export type Word = {
  word: string;
  begin: number;
  end: number;
  charBegin: number;
  charEnd: number;
};

export const WORDS: Word[] = [];
export const AUDIO_LENGTH_MS = 0;
